### ISSUE TITLE
Fix "Something went wrong" issue

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Forkify-JS#1]
There's an error when we search a recipe like "pizza". It says "Something wrong with the search..." and doesn't load the recipes.

![image](https://user-images.githubusercontent.com/11731837/65629843-c95df080-dff1-11e9-95b2-f07c5dfe85fa.png)

Inspect the problem, add a fix and report it back here with a working solution explaining the cause and how you fixed it.

**Comment by BonesyWonesy** [comment]
You've reached your API limit of requests I think @Kvaibhav01 :

https://www.food2fork.com/api/search?key=462b1cc8d4f2730081462fbc65136320&q=chicken%20breast&page=2

Response: {"error": "limit"}

**Comment by Kvaibhav01** [comment]
@BonesyWonesy, yes just saw that. It resets the limit after a day. Thank you for your help. 😄
