### ISSUE TITLE
Fix the uncaught error (in promise) for favourite recipes

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Forkify-JS#2]
Currently, after adding a recipe as a favorite, when we click on a favorite recipe, the app crashes with the following error:

![image](https://user-images.githubusercontent.com/11731837/65630186-89e3d400-dff2-11e9-9222-cb74e136eacf.png)

Inspect the problem, add a fix and report it back here with a working solution explaining the cause and how you fixed it.

**Comment by jesujcastillom** [comment]
I could tackle this bug if you'd like.
