### ISSUE TITLE
Make the webpage responsive

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Forkify-JS#3]
The webpage is not responsive. Add responsiveness with breakpoints for tablet and mobile.

**Comment by BarnikRay** [comment]
I would like to work on this issue

**Comment by Kvaibhav01** [comment]
@BarnikRay sure, go ahead.

**Comment by BarnikRay** [comment]
Hi.. how would you like the view to be for mobiles?

**Comment by Kvaibhav01** [comment]
### Header

- [ ] Place the search bar at the top.
- [ ] The favorite section to the right.
- [ ] The logo at top of the search bar.

### Results
- [ ] Under the header, place the results section, change elements accordingly.

### Recipe

- [ ] Under the results, place the recipe section, change elements accordingly.

### Shopping list

- [ ] Under the recipe, place the shopping list section, change elements accordingly.

**Comment by BarnikRay** [comment]
okay thanks..
